// AUTO-GENERATED — do not edit by hand.
//
// This file is regenerated by `scripts/gen-types.ps1`, which reads the
// Pydantic models in `daemon/synapse_daemon/models.py` and writes equivalent
// TypeScript declarations here. CI fails if this file is stale (Contract #8).
//
// Until Milestone B wires the generator, this placeholder mirrors the current
// shapes by hand so the renderer can type-check.

import type { ErrorEnvelope } from './error-types';

export type EntityStatus =
  | 'idle'
  | 'launching'
  | 'launched'
  | 'stopping'
  | 'stopped'
  | 'error';

export type AuditSource = 'desktop' | 'mobile' | 'tray' | 'cli' | 'auto';

export interface ErrorRef {
  code: string;
  message: string;
  occurred_at: string; // ISO 8601 UTC
}

export interface BaseEntity {
  id: string; // kebab-case (Contract #10)
  name: string;
  status: EntityStatus;
  last_error: ErrorRef | null;
  created_at: string;
  updated_at: string;
  last_transition_at: string;
}

export interface StateTransition {
  entity_id: string;
  from_status: EntityStatus;
  to_status: EntityStatus;
  at: string;
  source: AuditSource;
  note: string | null;
}

export interface HealthResponse {
  ok: boolean;
  version: string;
  started_at: string;
  contracts: number[];
}

// ── Round 2 contract models (#17–#28) ────────────────────────────────────

export type HealthState = 'unknown' | 'healthy' | 'degraded' | 'unhealthy';

export interface HealthProbe {
  kind: 'none' | 'http' | 'tcp' | 'command';
  target: string | null;
  interval_seconds: number;
  timeout_seconds: number;
  expect_status: number | null;
  consecutive_failures_to_unhealthy: number;
}

export interface HealthSnapshot {
  project_id: string;
  state: HealthState;
  last_probed_at: string | null;
  last_state_change_at: string;
  consecutive_failures: number;
  last_error: string | null;
}

export type RestartMode = 'never' | 'on-failure' | 'always';

export interface RestartPolicy {
  mode: RestartMode;
  max_retries: number;
  initial_backoff_seconds: number;
  max_backoff_seconds: number;
}

export interface ResourceSnapshot {
  entity_type: string;
  entity_id: string;
  pid: number;
  cpu_percent: number;
  rss_mb: number;
  sampled_at: string;
}

export interface ResourceCaps {
  max_rss_mb: number | null;
  max_cpu_percent: number | null;
}

export type NotificationLevel = 'info' | 'success' | 'warning' | 'error';

export interface Notification {
  event_kind: string;
  level: NotificationLevel;
  title: string;
  body: string;
  entity_type: string | null;
  entity_id: string | null;
  timestamp_utc: string;
  action_url: string | null;
}

export interface EnvVar {
  key: string;
  value: string | null;   // "(set)" placeholder for secrets after first save (Contract #25)
  secret: boolean;
  description: string | null;
}

export interface SnapshotPayload {
  synapse_version: string;
  format_version: number;
  schema_migration: number;
  exported_at: string;
  projects: Record<string, unknown>[];
  tools: Record<string, unknown>[];
  settings: Record<string, unknown>;
  audit_log_tail: Record<string, unknown>[];
  /** Project+key pairs whose secret values were not exported. */
  secret_keys: { project_id: string; key: string }[];
}

export interface RestoreReport {
  projects_created: number;
  projects_updated: number;
  tools_created: number;
  tools_updated: number;
  settings_changed: number;
  secrets_needing_reentry: { project_id: string; key: string }[];
  warnings: string[];
}

// ── Projects (Milestone D) ───────────────────────────────────────────────

export interface Project {
  id: string;
  name: string;
  path: string;
  launch_cmd: string;
  env: EnvVar[];
  icon: string | null;
  thumbnail: string | null;
  description: string | null;
  category: string | null;
  health: HealthProbe;
  restart: RestartPolicy;
  resource_caps: ResourceCaps;
  expected_port: number | null;
  status: EntityStatus;
  last_error: ErrorRef | null;
  current_health: HealthState;
  last_health_at: string | null;
  created_at: string;
  updated_at: string;
  last_transition_at: string;
}

export interface ProjectUpdate {
  name?: string;
  path?: string;
  launch_cmd?: string;
  icon?: string;
  thumbnail?: string;
  description?: string;
  category?: string;
  health?: HealthProbe;
  restart?: RestartPolicy;
  resource_caps?: ResourceCaps;
  expected_port?: number;
  env?: EnvVar[];
}

export interface ProjectListResponse {
  projects: Project[];
}

// Re-export ErrorEnvelope for ergonomics. (It's defined in error-types.ts
// because it's referenced before the generator runs.)
export type { ErrorEnvelope };
