// AUTO-GENERATED — do not edit by hand.
//
// This file is regenerated by `scripts/gen-types.ps1`, which reads the
// Pydantic models in `daemon/synapse_daemon/models.py` and writes equivalent
// TypeScript declarations here. CI fails if this file is stale (Contract #8).
//
// Until Milestone B wires the generator, this placeholder mirrors the current
// shapes by hand so the renderer can type-check.

import type { ErrorEnvelope } from './error-types';

export type EntityStatus =
  | 'idle'
  | 'launching'
  | 'launched'
  | 'stopping'
  | 'stopped'
  | 'error';

export type AuditSource = 'desktop' | 'mobile' | 'tray' | 'cli' | 'auto';

export interface ErrorRef {
  code: string;
  message: string;
  occurred_at: string; // ISO 8601 UTC
}

export interface BaseEntity {
  id: string; // kebab-case (Contract #10)
  name: string;
  status: EntityStatus;
  last_error: ErrorRef | null;
  created_at: string;
  updated_at: string;
  last_transition_at: string;
}

export interface StateTransition {
  entity_id: string;
  from_status: EntityStatus;
  to_status: EntityStatus;
  at: string;
  source: AuditSource;
  note: string | null;
}

export interface HealthResponse {
  ok: boolean;
  version: string;
  started_at: string;
  contracts: number[];
}

// ── Round 2 contract models (#17–#28) ────────────────────────────────────

export type HealthState = 'unknown' | 'healthy' | 'degraded' | 'unhealthy';

export interface HealthProbe {
  kind: 'none' | 'http' | 'tcp' | 'command';
  target: string | null;
  interval_seconds: number;
  timeout_seconds: number;
  expect_status: number | null;
  consecutive_failures_to_unhealthy: number;
}

export interface HealthSnapshot {
  project_id: string;
  state: HealthState;
  last_probed_at: string | null;
  last_state_change_at: string;
  consecutive_failures: number;
  last_error: string | null;
}

export type RestartMode = 'never' | 'on-failure' | 'always';

export interface RestartPolicy {
  mode: RestartMode;
  max_retries: number;
  initial_backoff_seconds: number;
  max_backoff_seconds: number;
}

export interface ResourceSnapshot {
  entity_type: string;
  entity_id: string;
  pid: number;
  cpu_percent: number;
  rss_mb: number;
  sampled_at: string;
}

export interface ResourceCaps {
  max_rss_mb: number | null;
  max_cpu_percent: number | null;
}

export type NotificationLevel = 'info' | 'success' | 'warning' | 'error';

export interface Notification {
  event_kind: string;
  level: NotificationLevel;
  title: string;
  body: string;
  entity_type: string | null;
  entity_id: string | null;
  timestamp_utc: string;
  action_url: string | null;
}

export interface EnvVar {
  key: string;
  value: string | null;   // "(set)" placeholder for secrets after first save (Contract #25)
  secret: boolean;
  description: string | null;
}

export interface SnapshotPayload {
  synapse_version: string;
  format_version: number;
  schema_migration: number;
  exported_at: string;
  projects: Record<string, unknown>[];
  tools: Record<string, unknown>[];
  settings: Record<string, unknown>;
  audit_log_tail: Record<string, unknown>[];
  /** Project+key pairs whose secret values were not exported. */
  secret_keys: { project_id: string; key: string }[];
}

export interface RestoreReport {
  projects_created: number;
  projects_updated: number;
  tools_created: number;
  tools_updated: number;
  settings_changed: number;
  secrets_needing_reentry: { project_id: string; key: string }[];
  warnings: string[];
}

// ── Profile hub + portable catalog state (v0.1.36-dev) ─────────────────

export interface LinkedIdentity {
  provider: string;
  email: string | null;
  identity_id: string | null;
}

export interface HostPresence {
  id: string;
  name: string;
  platform: string;
  current_host: boolean;
  last_seen_at: string;
  created_at: string;
  updated_at: string;
}

export interface ServiceConnection {
  id: string;
  provider: string;
  display_name: string;
  mode: string;
  portability: string;
  status: string;
  details: Record<string, unknown>;
  last_verified_at: string | null;
  last_host_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface CatalogPreferenceItem {
  item_key: string;
  kind: string;
  item_id: string;
  favorite: boolean;
  last_used_at: string | null;
  use_count: number;
  last_installed_at: string | null;
  installed_host_ids: string[];
  installed_here: boolean;
  previously_installed: boolean;
  used_before: boolean;
  updated_at: string;
}

export interface CatalogPreferenceState {
  current_host_id: string;
  items: CatalogPreferenceItem[];
  favorite_keys: string[];
  sync_enabled: boolean;
  signed_in: boolean;
  last_sync_at: string | null;
  last_sync_error: string | null;
}

export interface ProfilePreferences {
  theme: string | null;
  sidebar_layout: Record<string, unknown> | null;
  sessions_quick_actions_collapsed: boolean | null;
  discover_recent_keys: string[];
  updated_at: string | null;
}

export interface ProfileSummary {
  signed_in: boolean;
  sync_enabled: boolean;
  sync_status: string;
  sync_backend: string;
  user_id: string | null;
  username: string | null;
  email: string | null;
  display_name: string | null;
  avatar_url: string | null;
  email_verified: boolean;
  account_provider: string | null;
  linked_identities: LinkedIdentity[];
  current_host: HostPresence;
  portable_connection_count: number;
  local_connection_count: number;
  last_sync_at: string | null;
  last_sync_error: string | null;
  available_auth_providers: string[];
  account_backend_reachable: boolean;
  preferences: ProfilePreferences;
}

// ── Projects (Milestone D) ───────────────────────────────────────────────

/** What a project IS (v0.1.19) -- drives the Apps page filter. */
export type ProjectKind =
  | 'app'
  | 'ui'
  | 'service'
  | 'mcp-server'
  | 'library'
  | 'script'
  | 'other';

export interface Project {
  id: string;
  name: string;
  path: string;
  launch_cmd: string;
  env: EnvVar[];
  icon: string | null;
  thumbnail: string | null;
  description: string | null;
  category: string | null;
  health: HealthProbe;
  restart: RestartPolicy;
  resource_caps: ResourceCaps;
  expected_port: number | null;
  group: string | null;
  tags: string[];
  pinned: boolean;
  discovered: boolean;
  kind: ProjectKind;
  status: EntityStatus;
  last_error: ErrorRef | null;
  current_health: HealthState;
  last_health_at: string | null;
  created_at: string;
  updated_at: string;
  last_transition_at: string;
}

// ── Auto-discovery (v0.1.8.5) ────────────────────────────────────────────

export interface LaunchCandidate {
  label: string;
  command: string;
  note: string | null;
}

export interface DetectedProject {
  path: string;
  suggested_id: string;
  name: string;
  stack: string;
  framework: string | null;
  suggested_launch_cmd: string | null;
  suggested_port: number | null;
  confidence: number;
  candidates: LaunchCandidate[];
  icon: string | null;
  description: string | null;
  markers: string[];
  /** Discovery's classification (v0.1.19). */
  kind: ProjectKind;
  already_registered: boolean;
}

export interface DiscoveryScanResponse {
  root: string;
  count: number;
  projects: DetectedProject[];
}

export interface ImportReport {
  imported: string[];
  skipped: { id: string; reason: string }[];
}

export interface ProjectUpdate {
  name?: string;
  path?: string;
  launch_cmd?: string;
  icon?: string;
  thumbnail?: string;
  description?: string;
  category?: string;
  health?: HealthProbe;
  restart?: RestartPolicy;
  resource_caps?: ResourceCaps;
  expected_port?: number;
  env?: EnvVar[];
  group?: string | null;
  tags?: string[];
  pinned?: boolean;
  kind?: ProjectKind;
}

export interface ProjectListResponse {
  projects: Project[];
}

// ── Audit log (Contract #11 · v0.1.17) ───────────────────────────────────

export interface AuditEntry {
  id: number;
  timestamp_utc: string;
  entity_type: string;
  entity_id: string | null;
  action: string;
  source: AuditSource;
  result: string; // 'success' | 'error'
  error_code: string | null;
  details: Record<string, unknown> | null;
}

export interface AuditListResponse {
  entries: AuditEntry[];
  total: number;
  limit: number;
  offset: number;
}

// ── Tool plugin system (Milestone F · v0.1.9) ────────────────────────────

export type ToolFieldType = 'number' | 'text' | 'path' | 'boolean';

export interface ToolField {
  key: string;
  type: ToolFieldType;
  label: string;
  required: boolean;
  placeholder: string | null;
  min: number | null;
  max: number | null;
  default: unknown;
  help: string | null;
}

export type ToolActionScope = 'tool' | 'item';

export interface ToolAction {
  id: string;
  label: string;
  handler: string | null;
  primary: boolean;
  danger: boolean;
  /** 'tool' = a card-level button; 'item' = rendered per live instance. */
  scope: ToolActionScope;
  /** Statuses in which this action is enabled. Empty = always enabled. */
  available_in: EntityStatus[];
  /** Declarative tier (v0.1.22): vetted primitive (e.g. 'url.open'). */
  primitive?: string | null;
  /** Primitive params (e.g. {url: 'https://...{port}'}). */
  params?: Record<string, unknown>;
}

export interface ToolManifest {
  id: string;
  name: string;
  category: string;
  icon: string;
  description: string;
  version: string;
  fields: ToolField[];
  actions: ToolAction[];
  /** True when a compiled-in handler backs this tool's actions. */
  runnable: boolean;
}

/** One live instance of a multi-instance tool (e.g. a Cloudtap tunnel). */
export interface ToolItem {
  id: string;
  label: string;
  status: EntityStatus;
  result: Record<string, unknown>;
  message: string | null;
  last_error: ErrorRef | null;
  created_at: string;
}

export interface ToolState {
  tool_id: string;
  status: EntityStatus;
  fields: Record<string, unknown>;
  result: Record<string, unknown>;
  /** Live instances — each gets its own row + per-instance actions. */
  items: ToolItem[];
  message: string | null;
  last_error: ErrorRef | null;
  updated_at: string;
}

/** One tool as the daemon serves it: its manifest plus live state. */
export interface ToolEntry {
  manifest: ToolManifest;
  state: ToolState;
}

export interface ToolListResponse {
  tools: ToolEntry[];
}

// ── Marketplace (v0.1.23 · ADR-0001 step 3) ──────────────────────────────

export type ToolTier = 'declarative' | 'handler';

export interface RegistryEntry {
  id: string;
  name: string;
  publisher: string;
  tier: ToolTier;
  category?: string | null;
  tags?: string[];
  featured?: boolean;
  sort_rank?: number;
  version: string;
  description: string;
  homepage: string | null;
  verified: boolean;
  manifest_url: string | null;
  /** Inline manifest body — when set, install can skip the HTTP fetch. */
  manifest_inline?: Record<string, unknown> | null;
}

export interface InstallReport {
  installed: string;
  tier: string | null;
  version: string | null;
  path: string;
  reload: { added: string[]; removed: string[]; kept: string[] };
}

export interface UninstallReport {
  uninstalled: string;
  reload: { added: string[]; removed: string[]; kept: string[] };
}

// ── Sessions-centric AI squads (v0.1.36-dev) ────────────────────────────

export type AgentVisibility = 'lead' | 'helper';

export type AgentContextMode = 'full' | 'standard' | 'minimal';

export type AgentRoleTier = 'boss' | 'supervisor' | 'worker';

export type AgentSquadStatus = 'active' | 'paused' | 'completed';

export type AgentWorkItemStatus =
  | 'queued'
  | 'running'
  | 'handoff'
  | 'blocked'
  | 'completed';

export interface AgentRoleTemplate {
  id: string;
  name: string;
  description: string;
  preferred_runtimes: string[];
  default_visibility: AgentVisibility;
  context_mode: AgentContextMode;
  role_tier: AgentRoleTier;
  can_delegate: boolean;
  prompt_preamble_md: string;
  enabled: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface AgentSquad {
  id: string;
  project_id: string;
  name: string;
  goal_md: string;
  status: AgentSquadStatus;
  lead_role_id: string | null;
  created_at: string;
  updated_at: string;
  last_activity_at: string;
}

export interface AgentWorkItem {
  id: string;
  squad_id: string;
  parent_id: string | null;
  title: string;
  instructions_md: string;
  status: AgentWorkItemStatus;
  assigned_role_id: string | null;
  personality_id: string | null;
  preferred_runtime: string | null;
  pty_session_id: string | null;
  summary_md: string | null;
  blockers_md: string | null;
  files_touched: string[];
  suggested_next_role: string | null;
  transcript_file_id: string | null;
  opened_in_tab: boolean;
  created_at: string;
  updated_at: string;
  completed_at: string | null;
}

export interface AgentSquadDetail {
  squad: AgentSquad;
  role_templates: AgentRoleTemplate[];
  work_items: AgentWorkItem[];
}

// ── Chat-first coder workspace (v0.1.36-dev) ────────────────────────────

export type CoderThreadStatus = 'active' | 'archived' | 'closed';

export type CoderMessageRole = 'user' | 'assistant' | 'system' | 'reviewer';

export type CoderReviewPassStatus = 'pending' | 'running' | 'completed' | 'failed';

export type CoderRunStatus =
  | 'created'
  | 'running'
  | 'completed'
  | 'failed'
  | 'crashed'
  | 'stopped'
  | 'unavailable';

export interface CoderWorkspacePreferences {
  advanced_terminal_enabled: boolean;
  raw_pty_enabled: boolean;
  updated_at: string;
}

export interface CoderThread {
  id: string;
  project_id: string;
  title: string;
  status: CoderThreadStatus;
  active_runtime_id: string | null;
  active_provider: string | null;
  active_model: string | null;
  workspace_context_mode: string;
  pinned: boolean;
  archived: boolean;
  thread_kind: string;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  last_message_at: string | null;
  last_run_at: string | null;
}

export interface CoderThreadSummary {
  thread: CoderThread;
  message_count: number;
  review_pass_count: number;
  run_count: number;
  last_message_preview: string;
}

export interface CoderMessage {
  id: string;
  thread_id: string;
  role: CoderMessageRole;
  content_md: string;
  runtime_id: string | null;
  provider: string | null;
  model: string | null;
  coder_run_id: string | null;
  artifact_ids: string[];
  usage_summary: Record<string, unknown>;
  benchmark_attempt_id: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface CoderRuntimeSwitch {
  id: string;
  thread_id: string;
  from_runtime_id: string | null;
  from_provider: string | null;
  from_model: string | null;
  to_runtime_id: string | null;
  to_provider: string | null;
  to_model: string | null;
  reason: string;
  created_at: string;
}

export interface CoderReviewPass {
  id: string;
  thread_id: string;
  requested_runtime_id: string | null;
  requested_provider: string | null;
  requested_model: string | null;
  status: CoderReviewPassStatus;
  title: string;
  summary_md: string;
  coder_run_id: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface CoderRun {
  id: string;
  thread_id: string | null;
  message_id: string | null;
  review_pass_id: string | null;
  runtime_id: string;
  provider: string;
  model: string;
  surface_kind: string;
  surface_profile_version: string;
  pty_session_id: string | null;
  project_id: string | null;
  benchmark_attempt_id: string | null;
  status: CoderRunStatus;
  started_at: string;
  first_input_at: string | null;
  first_output_at: string | null;
  ended_at: string | null;
  exit_code: number | null;
  input_event_count: number;
  output_event_count: number;
  used_any_input: boolean;
  used_any_output: boolean;
  crash_reason: string | null;
  workspace_context_mode: string;
  attachments_count: number;
  hidden_context_hash: string | null;
  workspace_overhead_bytes: number;
  context_items_injected: number;
  metadata: Record<string, unknown>;
}

export interface CoderThreadDetail {
  thread: CoderThread;
  messages: CoderMessage[];
  runtime_switches: CoderRuntimeSwitch[];
  review_passes: CoderReviewPass[];
  linked_runs: CoderRun[];
}

export interface CoderWorkspaceContext {
  thread: CoderThread;
  recent_messages: CoderMessage[];
  review_passes: CoderReviewPass[];
  linked_runs: CoderRun[];
  files_count: number;
  recent_file_ids: string[];
  records_summary: Record<string, number>;
  available_actions: string[];
  preferences: CoderWorkspacePreferences;
}

// ── PTY sessions (v0.1.25 / v0.1.26 · ADR-0002 Phase A) ──────────────────

export interface PtySessionSummary {
  session_id: string;
  argv: string[];
  cwd: string | null;
  started_at: string;
  exit_code: number | null;
  rows: number;
  cols: number;
  project_id: string | null;
}

export interface PtySessionListResponse {
  sessions: PtySessionSummary[];
}

export interface PtySessionDetail extends PtySessionSummary {
  /** Base64-encoded tail of the output ring buffer (cap: 64 KiB). */
  scrollback: string;
}

export interface PtySpawnRequest {
  argv: string[];
  cwd?: string | null;
  env?: Record<string, string> | null;
  rows?: number;
  cols?: number;
}

export interface RegistryIndex {
  version: number;
  generated_at: string | null;
  tools: RegistryEntry[];
}

export interface MarketplaceResponse {
  source: { kind: 'url' | 'file'; location: string };
  registry: RegistryIndex;
  installed_ids: string[];
  cached: boolean;
}

// ── Project files (ADR-0003 Phase A · v0.1.30/31) ────────────────────────

export type ProjectFileSource = 'upload' | 'transcript' | 'chatgpt-import';
export type ScanResult = 'clean' | 'blocked' | 'unavailable' | null;

export interface ProjectFile {
  id: string;
  project_id: string | null;
  original_name: string;
  on_disk_name: string;
  mime: string;
  size_bytes: number;
  sha256: string;
  source: ProjectFileSource;
  source_session: string | null;
  uploaded_at: string;
  deleted_at: string | null;
  scan_result: ScanResult;
  scan_engine: string | null;
  duplicate_of: string | null;
}

export interface ProjectFilesListResponse {
  files: ProjectFile[];
}

export interface UploadFileResult {
  ok: boolean;
  id?: string;
  original_name: string;
  size_bytes?: number;
  mime?: string;
  sha256?: string;
  scan_result?: ScanResult;
  duplicate_of?: string | null;
  reason?: string;
}

export interface UploadFilesResponse {
  files: UploadFileResult[];
}

// Re-export ErrorEnvelope for ergonomics. (It's defined in error-types.ts
// because it's referenced before the generator runs.)
export type { ErrorEnvelope };
