// AUTO-GENERATED — do not edit by hand.
//
// This file is regenerated by `scripts/gen-types.ps1`, which reads the
// Pydantic models in `daemon/synapse_daemon/models.py` and writes equivalent
// TypeScript declarations here. CI fails if this file is stale (Contract #8).
//
// Until Milestone B wires the generator, this placeholder mirrors the current
// shapes by hand so the renderer can type-check.

import type { ErrorEnvelope } from './error-types';

export type EntityStatus =
  | 'idle'
  | 'launching'
  | 'launched'
  | 'stopping'
  | 'stopped'
  | 'error';

export type AuditSource = 'desktop' | 'mobile' | 'tray' | 'cli' | 'auto';

export interface ErrorRef {
  code: string;
  message: string;
  occurred_at: string; // ISO 8601 UTC
}

export interface BaseEntity {
  id: string; // kebab-case (Contract #10)
  name: string;
  status: EntityStatus;
  last_error: ErrorRef | null;
  created_at: string;
  updated_at: string;
  last_transition_at: string;
}

export interface StateTransition {
  entity_id: string;
  from_status: EntityStatus;
  to_status: EntityStatus;
  at: string;
  source: AuditSource;
  note: string | null;
}

export interface HealthResponse {
  ok: boolean;
  version: string;
  started_at: string;
  contracts: number[];
}

// ── Round 2 contract models (#17–#28) ────────────────────────────────────

export type HealthState = 'unknown' | 'healthy' | 'degraded' | 'unhealthy';

export interface HealthProbe {
  kind: 'none' | 'http' | 'tcp' | 'command';
  target: string | null;
  interval_seconds: number;
  timeout_seconds: number;
  expect_status: number | null;
  consecutive_failures_to_unhealthy: number;
}

export interface HealthSnapshot {
  project_id: string;
  state: HealthState;
  last_probed_at: string | null;
  last_state_change_at: string;
  consecutive_failures: number;
  last_error: string | null;
}

export type RestartMode = 'never' | 'on-failure' | 'always';

export interface RestartPolicy {
  mode: RestartMode;
  max_retries: number;
  initial_backoff_seconds: number;
  max_backoff_seconds: number;
}

export interface ResourceSnapshot {
  entity_type: string;
  entity_id: string;
  pid: number;
  cpu_percent: number;
  rss_mb: number;
  sampled_at: string;
}

export interface ResourceCaps {
  max_rss_mb: number | null;
  max_cpu_percent: number | null;
}

export type NotificationLevel = 'info' | 'success' | 'warning' | 'error';

export interface Notification {
  event_kind: string;
  level: NotificationLevel;
  title: string;
  body: string;
  entity_type: string | null;
  entity_id: string | null;
  timestamp_utc: string;
  action_url: string | null;
}

export interface EnvVar {
  key: string;
  value: string | null;   // "(set)" placeholder for secrets after first save (Contract #25)
  secret: boolean;
  description: string | null;
}

export interface SnapshotPayload {
  synapse_version: string;
  format_version: number;
  schema_migration: number;
  exported_at: string;
  projects: Record<string, unknown>[];
  tools: Record<string, unknown>[];
  settings: Record<string, unknown>;
  audit_log_tail: Record<string, unknown>[];
  /** Project+key pairs whose secret values were not exported. */
  secret_keys: { project_id: string; key: string }[];
}

export interface RestoreReport {
  projects_created: number;
  projects_updated: number;
  tools_created: number;
  tools_updated: number;
  settings_changed: number;
  secrets_needing_reentry: { project_id: string; key: string }[];
  warnings: string[];
}

// ── Projects (Milestone D) ───────────────────────────────────────────────

/** What a project IS (v0.1.19) -- drives the Apps page filter. */
export type ProjectKind =
  | 'app'
  | 'ui'
  | 'service'
  | 'mcp-server'
  | 'library'
  | 'script'
  | 'other';

export interface Project {
  id: string;
  name: string;
  path: string;
  launch_cmd: string;
  env: EnvVar[];
  icon: string | null;
  thumbnail: string | null;
  description: string | null;
  category: string | null;
  health: HealthProbe;
  restart: RestartPolicy;
  resource_caps: ResourceCaps;
  expected_port: number | null;
  group: string | null;
  tags: string[];
  pinned: boolean;
  discovered: boolean;
  kind: ProjectKind;
  status: EntityStatus;
  last_error: ErrorRef | null;
  current_health: HealthState;
  last_health_at: string | null;
  created_at: string;
  updated_at: string;
  last_transition_at: string;
}

// ── Auto-discovery (v0.1.8.5) ────────────────────────────────────────────

export interface LaunchCandidate {
  label: string;
  command: string;
  note: string | null;
}

export interface DetectedProject {
  path: string;
  suggested_id: string;
  name: string;
  stack: string;
  framework: string | null;
  suggested_launch_cmd: string | null;
  suggested_port: number | null;
  confidence: number;
  candidates: LaunchCandidate[];
  icon: string | null;
  description: string | null;
  markers: string[];
  /** Discovery's classification (v0.1.19). */
  kind: ProjectKind;
  already_registered: boolean;
}

export interface DiscoveryScanResponse {
  root: string;
  count: number;
  projects: DetectedProject[];
}

export interface ImportReport {
  imported: string[];
  skipped: { id: string; reason: string }[];
}

export interface ProjectUpdate {
  name?: string;
  path?: string;
  launch_cmd?: string;
  icon?: string;
  thumbnail?: string;
  description?: string;
  category?: string;
  health?: HealthProbe;
  restart?: RestartPolicy;
  resource_caps?: ResourceCaps;
  expected_port?: number;
  env?: EnvVar[];
  group?: string | null;
  tags?: string[];
  pinned?: boolean;
  kind?: ProjectKind;
}

export interface ProjectListResponse {
  projects: Project[];
}

// ── Audit log (Contract #11 · v0.1.17) ───────────────────────────────────

export interface AuditEntry {
  id: number;
  timestamp_utc: string;
  entity_type: string;
  entity_id: string | null;
  action: string;
  source: AuditSource;
  result: string; // 'success' | 'error'
  error_code: string | null;
  details: Record<string, unknown> | null;
}

export interface AuditListResponse {
  entries: AuditEntry[];
  total: number;
  limit: number;
  offset: number;
}

// ── Tool plugin system (Milestone F · v0.1.9) ────────────────────────────

export type ToolFieldType = 'number' | 'text' | 'path' | 'boolean';

export interface ToolField {
  key: string;
  type: ToolFieldType;
  label: string;
  required: boolean;
  placeholder: string | null;
  min: number | null;
  max: number | null;
  default: unknown;
  help: string | null;
}

export type ToolActionScope = 'tool' | 'item';

export interface ToolAction {
  id: string;
  label: string;
  handler: string | null;
  primary: boolean;
  danger: boolean;
  /** 'tool' = a card-level button; 'item' = rendered per live instance. */
  scope: ToolActionScope;
  /** Statuses in which this action is enabled. Empty = always enabled. */
  available_in: EntityStatus[];
  /** Declarative tier (v0.1.22): vetted primitive (e.g. 'url.open'). */
  primitive?: string | null;
  /** Primitive params (e.g. {url: 'https://...{port}'}). */
  params?: Record<string, unknown>;
}

export interface ToolManifest {
  id: string;
  name: string;
  category: string;
  icon: string;
  description: string;
  version: string;
  fields: ToolField[];
  actions: ToolAction[];
  /** True when a compiled-in handler backs this tool's actions. */
  runnable: boolean;
}

/** One live instance of a multi-instance tool (e.g. a Cloudtap tunnel). */
export interface ToolItem {
  id: string;
  label: string;
  status: EntityStatus;
  result: Record<string, unknown>;
  message: string | null;
  last_error: ErrorRef | null;
  created_at: string;
}

export interface ToolState {
  tool_id: string;
  status: EntityStatus;
  fields: Record<string, unknown>;
  result: Record<string, unknown>;
  /** Live instances — each gets its own row + per-instance actions. */
  items: ToolItem[];
  message: string | null;
  last_error: ErrorRef | null;
  updated_at: string;
}

/** One tool as the daemon serves it: its manifest plus live state. */
export interface ToolEntry {
  manifest: ToolManifest;
  state: ToolState;
}

export interface ToolListResponse {
  tools: ToolEntry[];
}

// ── Marketplace (v0.1.23 · ADR-0001 step 3) ──────────────────────────────

export type ToolTier = 'declarative' | 'handler';

export interface RegistryEntry {
  id: string;
  name: string;
  publisher: string;
  tier: ToolTier;
  version: string;
  description: string;
  homepage: string | null;
  verified: boolean;
  manifest_url: string | null;
  /** Inline manifest body — when set, install can skip the HTTP fetch. */
  manifest_inline?: Record<string, unknown> | null;
}

export interface InstallReport {
  installed: string;
  tier: string | null;
  version: string | null;
  path: string;
  reload: { added: string[]; removed: string[]; kept: string[] };
}

export interface UninstallReport {
  uninstalled: string;
  reload: { added: string[]; removed: string[]; kept: string[] };
}

// ── PTY sessions (v0.1.25 / v0.1.26 · ADR-0002 Phase A) ──────────────────

export interface PtySessionSummary {
  session_id: string;
  argv: string[];
  cwd: string | null;
  started_at: string;
  exit_code: number | null;
  rows: number;
  cols: number;
}

export interface PtySessionListResponse {
  sessions: PtySessionSummary[];
}

export interface PtySessionDetail extends PtySessionSummary {
  /** Base64-encoded tail of the output ring buffer (cap: 64 KiB). */
  scrollback: string;
}

export interface PtySpawnRequest {
  argv: string[];
  cwd?: string | null;
  env?: Record<string, string> | null;
  rows?: number;
  cols?: number;
}

export interface RegistryIndex {
  version: number;
  generated_at: string | null;
  tools: RegistryEntry[];
}

export interface MarketplaceResponse {
  source: { kind: 'url' | 'file'; location: string };
  registry: RegistryIndex;
  installed_ids: string[];
  cached: boolean;
}

// ── Project files (ADR-0003 Phase A · v0.1.30/31) ────────────────────────

export type ProjectFileSource = 'upload' | 'transcript' | 'chatgpt-import';
export type ScanResult = 'clean' | 'blocked' | 'unavailable' | null;

export interface ProjectFile {
  id: string;
  project_id: string | null;
  original_name: string;
  on_disk_name: string;
  mime: string;
  size_bytes: number;
  sha256: string;
  source: ProjectFileSource;
  source_session: string | null;
  uploaded_at: string;
  deleted_at: string | null;
  scan_result: ScanResult;
  scan_engine: string | null;
  duplicate_of: string | null;
}

export interface ProjectFilesListResponse {
  files: ProjectFile[];
}

export interface UploadFileResult {
  ok: boolean;
  id?: string;
  original_name: string;
  size_bytes?: number;
  mime?: string;
  sha256?: string;
  scan_result?: ScanResult;
  duplicate_of?: string | null;
  reason?: string;
}

export interface UploadFilesResponse {
  files: UploadFileResult[];
}

// Re-export ErrorEnvelope for ergonomics. (It's defined in error-types.ts
// because it's referenced before the generator runs.)
export type { ErrorEnvelope };
