"""Execute a blueprint: build each piece locally, prove it, assemble, and report honestly.

This is where every earlier phase meets. Each piece is generated by a local model, but the
model is given far more than a prompt:

* the **contract** it must satisfy, and the real interfaces of the modules it imports, read
  off the files that already exist rather than assumed
* the **UI kit and partials**, copied into the workspace, so presentation is referenced
  instead of invented
* an **acceptance test** written from the blueprint, not by the model
* the **web checks**, which render the result and attack it

The orchestration is ordinary Python throughout. That is the measured finding this whole
design rests on: a coding model called directly solves the benchmark tasks, and the same model
wrapped in a small-model agent loop solves a third of them, because choosing a tool, formatting
a call and relaying a spec are four chances to fail that have nothing to do with coding.

What it will not do is claim success it cannot prove. A piece whose checks did not run is
reported as `not_run`, and a build with unmet checks is not called passing.
"""

from __future__ import annotations

import shutil
import time
from pathlib import Path
from typing import Any, Callable

from pydantic import BaseModel, Field

from .. import blueprints as bp_mod
from ..blueprints import Blueprint, CheckKind, Piece
from ..local_pipeline import run_pipeline
from . import contracts as contracts_mod
from .partials import KIT_DIR

SCAFFOLD_DIR = Path(__file__).parent


class PieceOutcome(BaseModel):
    name: str
    passed: bool = False
    escalated: bool = False
    repairs: int = 0
    seconds: float = 0.0
    local_tokens: int = 0
    stop_reason: str = ""
    checks: dict[str, str] = Field(default_factory=dict)
    escalation_packet: str = ""
    test_source: str = ""
    """The test that actually decided this piece's verdict.

    Kept because a pass is only as trustworthy as the test behind it, and the first build
    of this blueprint reported `passwords` as passing with zero repairs while its
    `verify_password` raised `NameError` on every call. The test that waved it through had
    already been overwritten by the next piece, so the false pass could not be explained
    afterwards - only observed. Recording it makes that diagnosable rather than mysterious.
    """


class BuildResult(BaseModel):
    blueprint_id: str
    workspace: str
    pieces: list[PieceOutcome] = Field(default_factory=list)
    passed: bool = False
    seconds: float = 0.0
    local_tokens: int = 0
    escalations: list[str] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)

    def summary(self) -> str:
        ok = sum(1 for p in self.pieces if p.passed)
        return (f"{ok}/{len(self.pieces)} pieces built locally, "
                f"{len(self.escalations)} escalation(s), {self.local_tokens} local tokens, "
                f"{self.seconds:.0f}s")


def _install_assets(workspace: Path) -> None:
    """Put the house style where generated code can import it.

    Copied rather than imported from the daemon package so the produced app is standalone -
    it has to run on a machine that has never heard of Synapse.
    """
    (workspace / "ui_kit").mkdir(parents=True, exist_ok=True)
    shutil.copy(KIT_DIR / "kit.css", workspace / "ui_kit" / "kit.css")

    partials_src = (SCAFFOLD_DIR / "partials.py").read_text(encoding="utf-8")
    # Rewrite the kit path: inside the daemon it sits in a package, in the generated app it
    # sits next door.
    partials_src = partials_src.replace(
        'KIT_DIR = Path(__file__).parent / "ui_kit"',
        'KIT_DIR = Path(__file__).parent / "ui_kit"')
    (workspace / "scaffold_partials.py").write_text(partials_src, encoding="utf-8")


def _contract_from_piece(piece: Piece) -> contracts_mod.ModuleContract | None:
    spec = piece.contract or {}
    fns = spec.get("functions") or []
    if not fns:
        return None
    return contracts_mod.ModuleContract(
        module=piece.module or piece.name,
        functions=[contracts_mod.FunctionSpec(name=f["name"], args=f.get("args", []),
                                              returns=f.get("returns", ""))
                   for f in fns],
        constants=spec.get("constants", []))


def _dependency_context(piece: Piece, workspace: Path) -> str:
    """The real interfaces of everything this piece imports.

    Withholding this is what made a model invent `storage.user_exists()` and re-invent it four
    times. The signatures are read off the generated files, so they describe what exists now
    rather than what was requested.
    """
    if not piece.depends_on:
        return ""
    blocks = []
    for dep in piece.depends_on:
        path = workspace / f"{dep}.py"
        if path.exists():
            blocks.append(contracts_mod.public_interface(path).as_prompt())
    if not blocks:
        return ""
    return ("\n\nThe modules you import ALREADY EXIST. Call only these functions - do not "
            "invent others; if something seems missing, compose it from what is here.\n\n"
            + "\n\n".join(blocks))


def _asset_context(piece: Piece) -> str:
    if CheckKind.WEB not in piece.checks:
        return ""
    example = (SCAFFOLD_DIR / "ui_kit" / "EXAMPLE_PAGE.py")
    if not example.exists():
        return ""
    return ("\n\nHere is a page written in the house style. Follow this shape exactly - it "
            "is what the checks expect:\n\n```python\n"
            + example.read_text(encoding="utf-8") + "\n```")


async def build_blueprint(
    blueprint: Blueprint,
    *,
    workspace: str | Path,
    coder_model: str = "",
    max_repairs: int = 10,
    on_event: Callable[[dict[str, Any]], None] | None = None,
) -> BuildResult:
    """Build every piece, in dependency order, verifying as it goes.

    ``max_repairs`` defaults high because every attempt is local and therefore free, and the
    contract assertions converge: measured on this blueprint, the storage piece went from
    three correct signatures to six across four repairs and was still improving when the
    budget ran out. The recurring-error guard stops a stuck loop long before this ceiling, so
    a generous budget costs nothing when it is not needed.
    """
    ws = Path(workspace).resolve()
    ws.mkdir(parents=True, exist_ok=True)
    _install_assets(ws)

    started = time.time()
    result = BuildResult(blueprint_id=blueprint.id, workspace=str(ws))

    def emit(kind: str, **rest: Any) -> None:
        if on_event:
            on_event({"type": kind, "blueprint": blueprint.id, **rest})

    for piece in _in_dependency_order(blueprint.pieces):
        emit("piece_started", piece=piece.name)
        piece_started = time.time()
        module = piece.module or piece.name

        full_spec = piece.spec + _dependency_context(piece, ws) + _asset_context(piece)

        # Turn the declared contract into assertions that run inside the repair loop, so a
        # wrong signature is fixed locally and free rather than escalated.
        expected = _contract_from_piece(piece)
        contract_test = ""
        if expected is not None and CheckKind.CONTRACT in piece.checks:
            contract_test = contracts_mod.contract_test_source(module, expected)

        # The blueprint's own scenario, run in the same file. Measured need: `storage` passed
        # its contract with all nine signatures correct while `create_user` returned None and
        # `get_user_by_email` returned a bare tuple without the password hash - so its only
        # caller could neither start a session nor check a password. Signatures describe the
        # door; only calling through it proves there is a room behind. The scenario is written
        # once into the blueprint and re-earns its cost on every later build.
        if piece.tests.strip():
            contract_test = (contract_test.rstrip() + "\n\n" + piece.tests.strip()
                             if contract_test else piece.tests.strip())

        pipeline = await run_pipeline(
            full_spec,
            workspace=ws,
            path=f"{module}.py",
            coder_model=coder_model or "",
            max_repairs=max_repairs,
            extra_test=contract_test,
            on_event=lambda e, p=piece.name: emit("pipeline", piece=p, **e),
        )

        outcome = PieceOutcome(
            name=piece.name,
            passed=pipeline.passed,
            repairs=len(pipeline.attempts),
            seconds=round(time.time() - piece_started, 1),
            stop_reason=pipeline.stop_reason,
            escalation_packet=pipeline.escalation_packet,
            test_source=pipeline.test_code,
        )

        # Contract check runs even when the unit test passed: a module can satisfy a
        # generated test and still expose the wrong signature to its callers, which is
        # precisely how two pieces ended up disagreeing about a field name.
        if CheckKind.CONTRACT in piece.checks:
            expected = _contract_from_piece(piece)
            if expected is None:
                outcome.checks["contract"] = "not_run: no contract declared"
            else:
                problems = contracts_mod.check_contract(ws / f"{module}.py", expected)
                outcome.checks["contract"] = "pass" if not problems else f"fail: {problems[0]}"
                if problems:
                    outcome.passed = False
                    outcome.stop_reason = problems[0]

        # Reported separately from the contract so the two cannot be confused. A piece can
        # pass the contract and fail the scenario - that combination is the whole reason the
        # scenario exists, and collapsing them into one tick would hide it again.
        outcome.checks["scenario"] = (
            ("pass" if pipeline.passed else "fail") if piece.tests.strip()
            else "not_run: no scenario declared")

        if not outcome.passed:
            outcome.escalated = True
            result.escalations.append(piece.name)

        result.pieces.append(outcome)
        emit("piece_finished", piece=piece.name, passed=outcome.passed)

    result.seconds = round(time.time() - started, 1)
    result.passed = all(p.passed for p in result.pieces)
    if not result.passed:
        result.notes.append(
            "Some pieces need a stronger model. Their escalation_packet fields are "
            "self-contained: requirement, current code, the real error.")
    return result


def _in_dependency_order(pieces: list[Piece]) -> list[Piece]:
    """Topological order, so a piece is built after what it imports.

    Falls back to declaration order on a cycle rather than raising - a bad manifest should
    produce a poor build with a clear failure, not an exception before anything runs.
    """
    by_name = {p.name: p for p in pieces}
    ordered: list[Piece] = []
    seen: set[str] = set()

    def visit(piece: Piece, trail: set[str]) -> None:
        if piece.name in seen or piece.name in trail:
            return
        trail.add(piece.name)
        for dep in piece.depends_on:
            if dep in by_name:
                visit(by_name[dep], trail)
        trail.discard(piece.name)
        if piece.name not in seen:
            seen.add(piece.name)
            ordered.append(piece)

    for piece in pieces:
        visit(piece, set())
    return ordered


def record_build(blueprint: Blueprint, result: BuildResult, score: dict[str, Any] | None
                 ) -> None:
    """Write what this build achieved back into the manifest."""
    bp_score = bp_mod.BlueprintScore(
        total=(score or {}).get("total", 0.0),
        max=(score or {}).get("max", 0.0),
        percent=(score or {}).get("percent", 0.0),
        categories={k: v.get("points", 0.0) if isinstance(v, dict) else v
                    for k, v in ((score or {}).get("categories") or {}).items()},
        measured_at=time.strftime("%Y-%m-%dT%H:%M:%S"),
        local_tokens=result.local_tokens,
        seconds=result.seconds,
        escalations=result.escalations,
    )
    bp_mod.record_score(blueprint.id, bp_score)
