import { useEffect, useState } from 'react';
import { Laptop, Monitor, RefreshCw } from 'lucide-react';
import { heartbeatLocalMachine, listMachines, renameMachine, type SynapseMachine } from '@shared/machines-client';
import { Button } from './ui/button';
import { Card } from './ui/card';

export function MyMachinesPanel():JSX.Element {
 const [machines,setMachines]=useState<SynapseMachine[]>([]); const [localId,setLocalId]=useState<string|null>(null); const [selectedId,setSelectedId]=useState<string|null>(null); const [busy,setBusy]=useState(true); const [error,setError]=useState<string|null>(null);
 async function refresh(){setBusy(true);setError(null);try{const local=await heartbeatLocalMachine();setLocalId(local.id);setMachines(await listMachines())}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void refresh()},[]);
 return <Card className='flex flex-col gap-4 overflow-hidden p-6'>
  <div className='flex items-start justify-between gap-3'><div><div className='flex items-center gap-2'><Monitor className='h-5 w-5 text-primary'/><h2 className='text-lg font-semibold'>My machines</h2></div><p className='mt-1 text-sm text-muted-foreground'>Hosts registered with this Synapse installation. Account-wide sync and remote execution are not yet verified.</p></div><Button variant='outline' size='sm' disabled={busy} onClick={()=>void refresh()}><RefreshCw className={'h-3.5 w-3.5 '+(busy?'animate-spin':'')}/>Refresh</Button></div>
  {error&&<p role='alert' className='text-sm text-destructive'>{error}</p>}
  <div className='grid gap-3 md:grid-cols-2'>{machines.map(m=><div key={m.id} className='relative overflow-hidden rounded-xl border border-border bg-secondary/20 p-4'><div className='absolute inset-x-8 top-0 h-px bg-gradient-to-r from-transparent via-primary/70 to-transparent'/><div className='flex items-center gap-3'><div className='flex h-10 w-10 items-center justify-center rounded-xl border border-primary/20 bg-primary/10'><Laptop className='h-5 w-5 text-primary'/></div><div className='min-w-0'><div className='truncate font-medium'>{m.name}</div><div className='text-xs text-muted-foreground'>{m.platform} · {m.architecture} · Synapse {m.synapse_version??'unknown'}</div></div><span className='ml-auto rounded-full bg-secondary px-2 py-1 text-[11px] font-medium text-foreground'>{m.id===localId?'This machine':'Registered host'}</span></div><p className='mt-3 text-xs text-muted-foreground'>Last reported: {new Date(m.last_seen_at).toLocaleString()}</p><div className='mt-3 flex flex-wrap gap-1.5'>{m.capabilities.map(c=><span key={c} className='rounded-md border border-border bg-background/50 px-2 py-1 text-[11px] text-muted-foreground'>{c}</span>)}</div></div>)}</div>
  {machines.length>0&&<div className='rounded-lg border border-border p-3'><label htmlFor='machine-select' className='text-sm font-medium'>Selected machine</label><select id='machine-select' className='mt-2 w-full rounded-md border border-border bg-background p-2 text-sm' value={selectedId??localId??machines[0].id} onChange={e=>setSelectedId(e.target.value)}>{machines.map(m=><option key={m.id} value={m.id}>{m.name}{m.id===localId?' (this machine)':''}</option>)}</select><div className='mt-2 flex flex-wrap gap-2'><Button type='button' variant='outline' size='sm' disabled={busy} onClick={async()=>{const id=selectedId??localId??machines[0].id; const current=machines.find(m=>m.id===id);if(!current)return;const name=window.prompt('Name this machine',current.name)?.trim();if(!name||name===current.name)return;try{setError(null);await renameMachine(id,name);await refresh()}catch(e){setError((e as Error).message)}}}>Rename machine</Button></div><p className='mt-2 text-xs text-muted-foreground'>Selection and naming work for hosts registered here. Remote execution is disabled until machine authentication and routing are independently verified.</p></div>}  {!busy&&machines.length===0&&<div className='rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground'>No Synapse hosts registered yet.</div>}
 </Card>
}
